In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
ary = np.arange(1,11).reshape(5,2)
print(ary)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [7]:
arr2D = np.array([[1,2],[4,5]])
print(arr2D)
print(type(arr2D))

[[1 2]
 [4 5]]
<class 'numpy.ndarray'>


In [11]:
arr3D = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3D)
print(type(arr3D))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


In [18]:
arr4D = np.array([[[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]]])
print(arr4D)
print(arr4D.ndim)

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]
   [13 14 15 16]]]]
4


In [15]:
#Check how many dimensions the arrays have

a = np.array([1,2,3,4,5])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2,3,4],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [16]:
arr = np.array([1,2,3,4])

print(arr[0])
print(arr[1])

1
2


In [21]:
#Accessing elements in array

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("8th element in matrix: ",arr[1,2])

8th element in matrix:  8


In [22]:
t = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(t[1,0,2])

9


In [29]:
#Check datatype

arr = np.array([1,2,3,4],dtype ="i1")

print(arr)
print(arr.dtype)

[1 2 3 4]
int8


In [34]:
#Slicing

arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[1:6:2])
print(arr[-4:-1])

[2 3 4 5]
[5 6 7]
[2 4 6]
[4 5 6]


In [36]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0,2:4])

[3 4]


In [37]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[1,0,1:])

[8 9]


In [38]:
#Making a copy (does not affect the original array)

arr = np.array([1,2,3,4,5])

x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [39]:
#Making a view (affects the original array)

arr = np.array([1,2,3,4,5])

x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [40]:
#Shaping arrays

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.shape) #output in (row,column) format

(2, 4)


In [45]:
#Reshaping arrays

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr,"\n")
newarray = arr.reshape(3,4)
print(newarray,"\n")
newa = arr.reshape(6,2)
print(newa,"\n")
new = arr.reshape(2,6)
print(new,"\n")

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 



In [48]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[4,5,6],[7,8,9],[10,11,12]]])

print(arr.shape)

(2, 3, 3)


In [52]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [53]:
#Flattening arrays

arr = np.array([[1,2,3],[4,5,6]])

new = arr.reshape(-1)
print(new)

[1 2 3 4 5 6]


In [60]:
#Iterating arrays

arr = np.array([1,2,3])

for x in arr:
    print(x)
print("\n")
    
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    for y in x:
        print(y)
print("\n")

1
2
3


1
2
3
4
5
6




In [61]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8


In [63]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [64]:
#Joining NumPy Arrays using Concatenation

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [76]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2),axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [68]:
#Searching Arrays

arr = np.array([1,2,3,4,5,4,4])

x = np.where(arr==4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [9]:
#Search Sorted

a = np.array([6,7,8,9])

x = np.searchsorted(a,5)

print(x)

0


In [16]:
a = np.array([6,7,8,9])

x = np.searchsorted(a,6,side='right')

print(x)

1


In [84]:
#Sorting arrays

arr = np.array([3,2,0,1])

print(np.sort(arr))

[0 1 2 3]


In [85]:
arr = np.array(['beta','omega','gamma','alpha'])

print(np.sort(arr))

['alpha' 'beta' 'gamma' 'omega']


In [89]:
arr = np.array(['apple','ball'])

print(np.sort(arr))

['apple' 'ball']


In [91]:
arr = np.array([[3,2,4],[5,0,1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [94]:
#Random Number Generation

from numpy import random as r

x = r.randint(100,size=(5))

print(x)

[52  7 62 63 23]


In [96]:
x = r.randint(50,size=(2,5))

print(x)

[[ 5 19 43  2  6]
 [34 21 48 18 48]]


In [105]:
x = r.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))

print(x)

[7 7 7 7 7 7 7 3 3 7 7 7 5 7 7 3 5 7 3 7 5 5 7 7 3 7 7 7 3 7 7 5 7 7 7 3 7
 7 3 5 7 5 5 7 7 7 5 7 5 7 7 7 7 7 5 5 7 7 5 7 5 5 7 7 7 3 5 7 7 5 7 7 3 5
 7 7 7 7 5 7 3 7 7 7 7 7 5 7 7 7 5 7 7 7 7 3 7 7 7 7]
